layout_spectrum: 0.8052276
name: powerpivot-powerquery
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7681282
  lightness: 0.4629005
  saturation: 0.8659359
  rhythmicContrast: 0.7580101
  brandColors:
    - '#C5BFBB'
    - '#09070A'
    - '#69645B'
    - '#0E6CD9'
    - '#244C2F'
typography_spectrum: 0.8001686
